apiVersion: v1
kind: Namespace
metadata:
  name: sciety
---
apiVersion: v1
data:
  ALLOW_SITE_CRAWLERS: "false"
  APP_CACHE: redis
  APP_ORIGIN: https://sciety-demo.elifesciences.org
  CACHE_HOST: sciety--demo--cache
  EXPERIMENT_ENABLED: ""
  FATHOM_SITE_ID: ""
  GOOGLE_TAG_MANAGER_ID: ""
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--frontend-env-fh4472m5ff
  namespace: sciety
---
apiVersion: v1
data:
  EXPERIMENT_ENABLED: ""
  INGESTION_TARGET_APP: https://sciety-demo.elifesciences.org
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--ingestion-env-772tg75gd8
  namespace: sciety
---
apiVersion: v1
data:
  key: dmFsdWU=
kind: Secret
metadata:
  name: ncrc-sheet-key
  namespace: sciety
---
apiVersion: v1
data:
  APP_SECRET: dW5zYWZlLXNlY3JldA==
  AUTH0_CALLBACK_URL: aHR0cHM6Ly9zdGFnaW5nLnNjaWV0eS5vcmcvYXV0aDAvY2FsbGJhY2s=
  AUTH0_CLIENT_ID: Ym9ndXMtYXV0aDAtY2xpZW50LWlk
  AUTH0_CLIENT_SECRET: Ym9ndXMtYXV0aDAtY2xpZW50LXNlY3JldA==
  AUTH0_DOMAIN: c2NpZXR5LXN0YWdpbmcuZXUuYXV0aDAuY29t
  CROSSREF_API_BEARER_TOKEN: Ym9ndXM=
  PGDATABASE: dGhlLWRhdGFiYXNlLW5hbWU=
  PGHOST: c2NpZXR5LS1kZW1vLS1kYXRhYmFzZQ==
  PGPASSWORD: dGhlLWRhdGFiYXNlLXBhc3N3b3Jk
  PGPORT: NTQzMg==
  PGUSER: dGhlLWRhdGFiYXNlLXVzZXI=
  SCIETY_TEAM_API_BEARER_TOKEN: bm90LXJlYWxseS1zZWNyZXQtYmVhcmVyLXRva2Vu
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--frontend-secret-m9m2fhdhc5
  namespace: sciety
type: Opaque
---
apiVersion: v1
data:
  CROSSREF_API_BEARER_TOKEN: Ym9ndXM=
  PRELIGHTS_FEED_KEY: Ym9ndXMtcHJlbGlnaHRzLWZlZWQta2V5
  SCIETY_TEAM_API_BEARER_TOKEN: bm90LXJlYWxseS1zZWNyZXQtYmVhcmVyLXRva2Vu
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--ingestion-secret-5hbcthhftd
  namespace: sciety
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: cache
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--cache
  namespace: sciety
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/component: cache
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--frontend
  namespace: sciety
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cache
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--cache
  namespace: sciety
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: cache
      app.kubernetes.io/instance: sciety--demo
      app.kubernetes.io/name: sciety
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cache
        app.kubernetes.io/instance: sciety--demo
        app.kubernetes.io/name: sciety
    spec:
      containers:
      - image: redis:7.2.0-alpine@sha256:5ddcd6e1a1ee0d3a2e9fe1abb427be987ab082e4756bdc513cd4293dacf05d27
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--frontend
  namespace: sciety
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: sciety--demo
      app.kubernetes.io/name: sciety
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: sciety--demo
        app.kubernetes.io/name: sciety
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: sciety--demo--frontend-env-fh4472m5ff
        - secretRef:
            name: sciety--demo--frontend-secret-m9m2fhdhc5
        image: sciety/sciety:c9ce6d413f5ee857b9b55b526e0e5846b66eaac0
        name: app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 1
        volumeMounts:
        - mountPath: /var/run/secrets/app
          name: gcp-ncrc-key
          readOnly: true
      volumes:
      - name: gcp-ncrc-key
        secret:
          secretName: ncrc-sheet-key
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: ingestion
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--ingestion
  namespace: sciety
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: ingestion
        app.kubernetes.io/instance: sciety--demo
        app.kubernetes.io/name: sciety
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: ingestion
            app.kubernetes.io/instance: sciety--demo
            app.kubernetes.io/name: sciety
        spec:
          containers:
          - command:
            - sh
            - -c
            - node ./build/ingest/update-event-data && wget --quiet https://hc-ping.com/bogus-healthchecks-ping-key/sciety-demo-ingestion
              || echo 'Done'
            envFrom:
            - configMapRef:
                name: sciety--demo--ingestion-env-772tg75gd8
            - secretRef:
                name: sciety--demo--ingestion-secret-5hbcthhftd
            image: sciety/sciety:c9ce6d413f5ee857b9b55b526e0e5846b66eaac0
            name: app
            volumeMounts:
            - mountPath: /var/run/secrets/app
              name: gcp-ncrc-key
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: gcp-ncrc-key
            secret:
              secretName: ncrc-sheet-key
  schedule: '*/30 * * * *'
  startingDeadlineSeconds: 720
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers "X-Forwarded-Proto: https";
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/name: sciety
  name: sciety--demo--frontend
  namespace: sciety
spec:
  rules:
  - host: sciety-demo.elifesciences.org
    http:
      paths:
      - backend:
          service:
            name: sciety--demo--frontend
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - sciety-demo.elifesciences.org
    - www.sciety-demo.elifesciences.org
    secretname: frontend--letsencrypt-cert
