apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../base"
  - "./frontend"
  - "./ingestion"

commonLabels:
  app.kubernetes.io/name: sciety
  app.kubernetes.io/instance: sciety--demo

namePrefix:
  sciety--demo--

configMapGenerator:
  - name: ingestion-env
    literals:
      - INGESTION_TARGET_APP=https://sciety-demo.elifesciences.org
      - EXPERIMENT_ENABLED=""