apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../base"

commonLabels:
  app.kubernetes.io/name: sciety
  app.kubernetes.io/instance: sciety--demo

namePrefix:
  sciety--demo--

images:
  - name: sciety/sciety
    newTag: c9ce6d413f5ee857b9b55b526e0e5846b66eaac0
  - name: redis
    newTag: 7.2.0-alpine
    digest: sha256:5ddcd6e1a1ee0d3a2e9fe1abb427be987ab082e4756bdc513cd4293dacf05d27

configMapGenerator:
  - name: frontend-env
    literals:
      - ALLOW_SITE_CRAWLERS=false
      - APP_ORIGIN=https://sciety-demo.elifesciences.org
      - APP_CACHE=redis
      - CACHE_HOST=sciety--demo--cache
      - EXPERIMENT_ENABLED=
      - FATHOM_SITE_ID=
      - GOOGLE_TAG_MANAGER_ID=
  - name: ingestion-env
    literals:
      - INGESTION_TARGET_APP=https://sciety-demo.elifesciences.org
      - EXPERIMENT_ENABLED=""

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: sciety-demo.elifesciences.org
      - op: replace
        path: /spec/tls/0/hosts/0
        value: sciety-demo.elifesciences.org
      - op: replace
        path: /spec/tls/0/hosts/1
        value: www.sciety-demo.elifesciences.org
    target:
      kind: Ingress
      name: frontend

secretGenerator:
  - name: frontend-secret
    envs:
      - "./frontend-secret.env"
  - name: ingestion-secret
    envs:
      - "./ingestion-secret.env"
