apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./foo-secret.yaml"
  - "./cache.yaml"
  - "./frontend.yaml"
  - "./ingestion.yaml"
  - "./ingress.yaml"

commonLabels:
  app.kubernetes.io/name: sciety
  app.kubernetes.io/instance: sciety--demo