apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./cache"
  - "./frontend"
  - "./ingestion"

commonLabels:
  app.kubernetes.io/name: sciety
  app.kubernetes.io/instance: sciety--demo