apiVersion: batch/v1
kind: CronJob
metadata:
  name: ingestion
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: sciety/sciety
            command:
            - sh
            - -c
            - node ./build/ingest/update-event-data && wget --quiet ${HEALTHCHECK_ENDPOINT} || echo 'Done'
            envFrom:
              - configMapRef:
                  name: ingestion-env
              - secretRef:
                  name: ingestion-secret
            volumeMounts:
            - mountPath: /var/run/secrets/app
              name: gcp-ncrc-key
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: gcp-ncrc-key
            secret:
              secretName: ncrc-sheet-key
  schedule: '*/30 * * * *'
  startingDeadlineSeconds: 720